CREATE DATABASE INVESTMENT_BRIDGE;

USE INVESTMENT_BRIDGE;

CREATE TABLE INVESTIDOR_PESSOA(

	CPF CHAR(14) PRIMARY KEY,
    NOME VARCHAR(50),
    TELEFONE VARCHAR(14),
    EMAIL VARCHAR(100)
);

CREATE TABLE INVESTIDOR_EMPRESA(

	CNPJ CHAR(15) PRIMARY KEY,
    NOME VARCHAR(50),
    TELEFONE VARCHAR(14),
    EMAIL VARCHAR(100)
);

CREATE TABLE CLIENTE_PESSOA(

	CPF CHAR(14) PRIMARY KEY,
    NOME VARCHAR(50),
    TELEFONE VARCHAR(14),
    EMAIL VARCHAR(100),
    ENDERECO VARCHAR(50)
);

CREATE TABLE CLIENTE_EMPRESA(

	CNPJ CHAR(15) PRIMARY KEY,
    NOME VARCHAR(50),
    TELEFONE VARCHAR(14),
    EMAIL VARCHAR(100),
    ENDERECO VARCHAR(50)
);

CREATE TABLE PROJETOS(

	COD INT PRIMARY KEY,
	NOME VARCHAR(50),
    TIPO VARCHAR(100),
    NECESSIDADE_INVESTIMENTO VARCHAR(200)
);

CREATE TABLE FINANCIAR(

	FK_INVESTIDOR_PESSOA_CPF CHAR(14),
    FK_INVESTIDOR_EMPRESA_CNPJ CHAR(15),
    FK_PROJETOS_COD INT,
    DATA DATE,
    VALORNEGOCIADO DOUBLE,
	FOREIGN KEY(FK_INVESTIDOR_PESSOA_CPF) REFERENCES INVESTIDOR_PESSOA(CPF),
    FOREIGN KEY(FK_INVESTIDOR_EMPRESA_CNPJ) REFERENCES INVESTIDOR_EMPRESA(CNPJ),
    FOREIGN KEY(FK_PROJETOS_COD) REFERENCES PROJETOS(COD),
    PRIMARY KEY(FK_INVESTIDOR_PESSOA_CPF, FK_INVESTIDOR_EMPRESA_CNPJ, FK_PROJETOS_COD)
);

CREATE TABLE CHAT(

	FK_INVESTIDOR_PESSOA_CPF CHAR(14),
    FK_INVESTIDOR_EMPRESA_CNPJ CHAR(15),
    FK_CLIENTE_PESSOA_CPF CHAR(14),
    FK_CLIENTE_EMPRESA_CNPJ CHAR(15),
    ARMAZENAR TEXT,
    FOREIGN KEY(FK_INVESTIDOR_PESSOA_CPF) REFERENCES INVESTIDOR_PESSOA(CPF),
    FOREIGN KEY(FK_INVESTIDOR_EMPRESA_CNPJ) REFERENCES INVESTIDOR_EMPRESA(CNPJ),
    FOREIGN KEY(FK_CLIENTE_PESSOA_CPF) REFERENCES CLIENTE_PESSOA(CPF),
    FOREIGN KEY(FK_CLIENTE_EMPRESA_CNPJ) REFERENCES CLIENTE_EMPRESA(CNPJ),
    PRIMARY KEY(FK_INVESTIDOR_PESSOA_CPF, FK_INVESTIDOR_EMPRESA_CNPJ, FK_CLIENTE_PESSOA_CPF, FK_CLIENTE_EMPRESA_CNPJ)
);

CREATE TABLE INVESTIDOR_EMPRESA_CLIENTE_EMPRESA(

	FK_INVESTIDOR_EMPRESA_CNPJ CHAR(15),
    FK_CLIENTE_EMPRESA_CNPJ CHAR(15),
	FOREIGN KEY(FK_INVESTIDOR_EMPRESA_CNPJ) REFERENCES INVESTIDOR_EMPRESA(CNPJ),
	FOREIGN KEY(FK_CLIENTE_EMPRESA_CNPJ) REFERENCES CLIENTE_EMPRESA(CNPJ),
    PRIMARY KEY(FK_INVESTIDOR_EMPRESA_CNPJ, FK_CLIENTE_EMPRESA_CNPJ)
);

CREATE TABLE INVESTIDOR_PESSOA_CLIENTE_PESSOA(

	FK_INVESTIDOR_PESSOA_CPF CHAR(14),
    FK_CLIENTE_PESSOA_CPF CHAR(14),
	FOREIGN KEY(FK_INVESTIDOR_PESSOA_CPF) REFERENCES INVESTIDOR_PESSOA(CPF),
	FOREIGN KEY(FK_CLIENTE_PESSOA_CPF) REFERENCES CLIENTE_PESSOA(CPF),
    PRIMARY KEY(FK_INVESTIDOR_PESSOA_CPF, FK_CLIENTE_PESSOA_CPF)
);

CREATE TABLE INVESTIDOR_EMPRESA_CLIENTE_PESSOA(

	FK_INVESTIDOR_EMPRESA_CNPJ CHAR(15),
    FK_CLIENTE_PESSOA_CPF CHAR(14),
	FOREIGN KEY(FK_INVESTIDOR_EMPRESA_CNPJ) REFERENCES INVESTIDOR_EMPRESA(CNPJ),
	FOREIGN KEY(FK_CLIENTE_PESSOA_CPF) REFERENCES CLIENTE_PESSOA(CPF),
    PRIMARY KEY(FK_INVESTIDOR_EMPRESA_CNPJ, FK_CLIENTE_PESSOA_CPF)
);

CREATE TABLE INVESTIDOR_PESSOA_CLIENTE_EMPRESA(

	FK_INVESTIDOR_PESSOA_CPF CHAR(14),
    FK_CLIENTE_EMPRESA_CNPJ CHAR(15),
	FOREIGN KEY(FK_INVESTIDOR_PESSOA_CPF) REFERENCES INVESTIDOR_PESSOA(CPF),
	FOREIGN KEY(FK_CLIENTE_EMPRESA_CNPJ) REFERENCES CLIENTE_EMPRESA(CNPJ),
    PRIMARY KEY(FK_INVESTIDOR_PESSOA_CPF, FK_CLIENTE_EMPRESA_CNPJ)
);